// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA48IFWPPoItF8gUo1q0fo2_tSeikYp1vY',
    appId: '1:217115580303:web:f83c61e557d10597445dfa',
    messagingSenderId: '217115580303',
    projectId: 'money-management-b1076',
    authDomain: 'money-management-b1076.firebaseapp.com',
    databaseURL: 'https://money-management-b1076-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'money-management-b1076.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-TJgy_3fE2uvArVz5VIjK0JIwqXHyegE',
    appId: '1:217115580303:android:a6ac5cc103e49e04445dfa',
    messagingSenderId: '217115580303',
    projectId: 'money-management-b1076',
    databaseURL: 'https://money-management-b1076-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'money-management-b1076.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvQw6Pe9ZF2COcpQPnCrcFRzqo0IpNWpk',
    appId: '1:217115580303:ios:6295eca37edd0399445dfa',
    messagingSenderId: '217115580303',
    projectId: 'money-management-b1076',
    databaseURL: 'https://money-management-b1076-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'money-management-b1076.appspot.com',
    iosClientId: '217115580303-aiik9a434d28k4qtneklha4pcva46qe8.apps.googleusercontent.com',
    iosBundleId: 'com.example.moneyManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvQw6Pe9ZF2COcpQPnCrcFRzqo0IpNWpk',
    appId: '1:217115580303:ios:6295eca37edd0399445dfa',
    messagingSenderId: '217115580303',
    projectId: 'money-management-b1076',
    databaseURL: 'https://money-management-b1076-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'money-management-b1076.appspot.com',
    iosClientId: '217115580303-aiik9a434d28k4qtneklha4pcva46qe8.apps.googleusercontent.com',
    iosBundleId: 'com.example.moneyManagement',
  );
}
